<a href="https://colab.research.google.com/github/April03exo/BSIS-2A_RAPANUT-APRIL-JOY-V./blob/main/Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array = np.array([1,2,3,4,5,6,8])
np.median(array)

4.0

In [ ]:
np.median(array)

4.0

In [41]:
np.min(array)

1

In [ ]:
np.max(array)

8

In [ ]:
std_dev = np.std(array)

In [ ]:
print(std_dev)

2.231499907401901


In [ ]:
np.sum(array)

29

In [ ]:
reshaped_array = array.reshape(1,7)

In [ ]:
print(reshaped_array)

[[1 2 3 4 5 6 8]]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [ ]:
concatenated = np.concatenate((array1,array2))

In [ ]:
print(concatenated)

[1 2 3 4 5 6]


In [ ]:
numbers = np.linspace(0, 10 ,5)

In [ ]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
range_data = np.arange(0,5,2)

In [ ]:
print(range_data)

[0 2 4]
